export const ADD_TOKEN = 'ADD_TOKEN'
export const ADD_PRINCIPAL = 'ADD_PRINCIPAL'
export const UPDATE_AVATAR = 'UPDATE_AVATAR'
export const UPDATE_GENDER = 'UPDATE_GENDER'
export const UPDATE_MOBILE = 'UPDATE_MOBILE'
export const LOAD_CONFIG = 'LOAD_CONFIG'
export const REDIRECT = 'REDIRECT'
export const LOGOUT = 'LOGOUT'
export const TESTING = 'TESTING'


export const CLEAN_SELECTED_PRODUCTS = 'CLEAN_SELECTED_PRODUCTS'
export const CLEAN_SELECTED_CUSTOMERS = 'CLEAN_SELECTED_CUSTOMERS'
